// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA78dFThZbU2aZ9vFk1AAVDkGfesqiKQCM',
    appId: '1:482644135306:web:fb520bb371ab260b08cc73',
    messagingSenderId: '482644135306',
    projectId: 'tatos-mynotes-flutter-project',
    authDomain: 'tatos-mynotes-flutter-project.firebaseapp.com',
    storageBucket: 'tatos-mynotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVyQ0gx4MqAG9IylbX0YgorxgDEYQXjcc',
    appId: '1:482644135306:android:9a2b97f3c5ab219708cc73',
    messagingSenderId: '482644135306',
    projectId: 'tatos-mynotes-flutter-project',
    storageBucket: 'tatos-mynotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3hZiN9sPUN13WGLAW8SnakreH4yINX24',
    appId: '1:482644135306:ios:c899b1139dabedce08cc73',
    messagingSenderId: '482644135306',
    projectId: 'tatos-mynotes-flutter-project',
    storageBucket: 'tatos-mynotes-flutter-project.appspot.com',
    iosClientId: '482644135306-lj6fgdr2lu2qggats2tviirfrnaq67sl.apps.googleusercontent.com',
    iosBundleId: 'com.tatosdev.mynotes',
  );
}
